//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise2_20180140103_Rama_Soni_Ravictor.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITI_UMY")]
    public interface ITI_UMY {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa[] GetAllMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        System.Threading.Tasks.Task<ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa[]> GetAllMahasiswaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa GetMahasiswaByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        System.Threading.Tasks.Task<ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa> GetMahasiswaByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        string CreateMahasiswa(ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CreateMahasiswaAsync(ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaResponse")]
        string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteByNIM", ReplyAction="http://tempuri.org/ITI_UMY/DeleteByNIMResponse")]
        string DeleteByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteByNIM", ReplyAction="http://tempuri.org/ITI_UMY/DeleteByNIMResponse")]
        System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CountMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CountMahasiswaResponse")]
        string CountMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CountMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CountMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CountMahasiswaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITI_UMYChannel : Exercise2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TI_UMYClient : System.ServiceModel.ClientBase<Exercise2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY>, Exercise2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY {
        
        public TI_UMYClient() {
        }
        
        public TI_UMYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa[] GetAllMahasiswa() {
            return base.Channel.GetAllMahasiswa();
        }
        
        public System.Threading.Tasks.Task<ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa[]> GetAllMahasiswaAsync() {
            return base.Channel.GetAllMahasiswaAsync();
        }
        
        public ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa GetMahasiswaByNIM(string nim) {
            return base.Channel.GetMahasiswaByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa> GetMahasiswaByNIMAsync(string nim) {
            return base.Channel.GetMahasiswaByNIMAsync(nim);
        }
        
        public string CreateMahasiswa(ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswa(mhs);
        }
        
        public System.Threading.Tasks.Task<string> CreateMahasiswaAsync(ServiceRest_20180140103_Rama_Soni_Ravictor.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswaAsync(mhs);
        }
        
        public string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswa(nim, nama, prodi, angkatan);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswaAsync(nim, nama, prodi, angkatan);
        }
        
        public string DeleteByNIM(string nim) {
            return base.Channel.DeleteByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim) {
            return base.Channel.DeleteByNIMAsync(nim);
        }
        
        public string CountMahasiswa() {
            return base.Channel.CountMahasiswa();
        }
        
        public System.Threading.Tasks.Task<string> CountMahasiswaAsync() {
            return base.Channel.CountMahasiswaAsync();
        }
    }
}
