//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mahasiswa", Namespace="http://schemas.datacontract.org/2004/07/ServiceRest_20180140103_Rama_Soni_Ravicto" +
        "r")]
    [System.SerializableAttribute()]
    public partial class Mahasiswa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string namaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string prodiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string angkatanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nama {
            get {
                return this.namaField;
            }
            set {
                if ((object.ReferenceEquals(this.namaField, value) != true)) {
                    this.namaField = value;
                    this.RaisePropertyChanged("nama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nim {
            get {
                return this.nimField;
            }
            set {
                if ((object.ReferenceEquals(this.nimField, value) != true)) {
                    this.nimField = value;
                    this.RaisePropertyChanged("nim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prodi {
            get {
                return this.prodiField;
            }
            set {
                if ((object.ReferenceEquals(this.prodiField, value) != true)) {
                    this.prodiField = value;
                    this.RaisePropertyChanged("prodi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string angkatan {
            get {
                return this.angkatanField;
            }
            set {
                if ((object.ReferenceEquals(this.angkatanField, value) != true)) {
                    this.angkatanField = value;
                    this.RaisePropertyChanged("angkatan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ITI_UMY")]
    public interface ITI_UMY {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa[] GetAllMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetAllMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/GetAllMahasiswaResponse")]
        System.Threading.Tasks.Task<Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa[]> GetAllMahasiswaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa GetMahasiswaByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/GetMahasiswaByNIM", ReplyAction="http://tempuri.org/ITI_UMY/GetMahasiswaByNIMResponse")]
        System.Threading.Tasks.Task<Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa> GetMahasiswaByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        string CreateMahasiswa(Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CreateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CreateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CreateMahasiswaAsync(Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa mhs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaResponse")]
        string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/UpdateMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/UpdateMahasiswaResponse")]
        System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteByNIM", ReplyAction="http://tempuri.org/ITI_UMY/DeleteByNIMResponse")]
        string DeleteByNIM(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/DeleteByNIM", ReplyAction="http://tempuri.org/ITI_UMY/DeleteByNIMResponse")]
        System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CountMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CountMahasiswaResponse")]
        string CountMahasiswa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITI_UMY/CountMahasiswa", ReplyAction="http://tempuri.org/ITI_UMY/CountMahasiswaResponse")]
        System.Threading.Tasks.Task<string> CountMahasiswaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITI_UMYChannel : Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TI_UMYClient : System.ServiceModel.ClientBase<Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY>, Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.ITI_UMY {
        
        public TI_UMYClient() {
        }
        
        public TI_UMYClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TI_UMYClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa[] GetAllMahasiswa() {
            return base.Channel.GetAllMahasiswa();
        }
        
        public System.Threading.Tasks.Task<Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa[]> GetAllMahasiswaAsync() {
            return base.Channel.GetAllMahasiswaAsync();
        }
        
        public Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa GetMahasiswaByNIM(string nim) {
            return base.Channel.GetMahasiswaByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa> GetMahasiswaByNIMAsync(string nim) {
            return base.Channel.GetMahasiswaByNIMAsync(nim);
        }
        
        public string CreateMahasiswa(Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswa(mhs);
        }
        
        public System.Threading.Tasks.Task<string> CreateMahasiswaAsync(Client2_20180140103_Rama_Soni_Ravictor.ServiceReference1.Mahasiswa mhs) {
            return base.Channel.CreateMahasiswaAsync(mhs);
        }
        
        public string UpdateMahasiswa(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswa(nim, nama, prodi, angkatan);
        }
        
        public System.Threading.Tasks.Task<string> UpdateMahasiswaAsync(string nim, string nama, string prodi, string angkatan) {
            return base.Channel.UpdateMahasiswaAsync(nim, nama, prodi, angkatan);
        }
        
        public string DeleteByNIM(string nim) {
            return base.Channel.DeleteByNIM(nim);
        }
        
        public System.Threading.Tasks.Task<string> DeleteByNIMAsync(string nim) {
            return base.Channel.DeleteByNIMAsync(nim);
        }
        
        public string CountMahasiswa() {
            return base.Channel.CountMahasiswa();
        }
        
        public System.Threading.Tasks.Task<string> CountMahasiswaAsync() {
            return base.Channel.CountMahasiswaAsync();
        }
    }
}
